name: Show system info

on:
  push:
    branches:
      - develop

jobs:
  info:
    runs-on: ubuntu-latest


    steps:
      - name: Show Linux info
        run: |
          whoami
          pwd
          uname -a
